### PR TITLE
Drop UniProt XML, use data.uniprot

### PR DESCRIPTION
**Pull request by eparejatobes**
- [ ] conversions should now go from the data.uniprot entry types to bio4j/bio4j (gene locations, comment topics, etc)
- [x] re-implement simple manipulations like the entry isoform id etc using the data.uniprot entry type
- [ ] add location parsing and conversion to reasonable 0-based half-open intervals

### CODE REVIEW

**Comment by eparejatobes** [comment]
Note that right now what is making all this slow is Titan itself; accessing all data for importing swissProt proteins takes ~40s, while adding it to the DB close to 10 times that

**Comment by eparejatobes** [comment]
I cannot make Titan faster than 3500 proteins/s. This means that TrEMBL will take (lower bound) ~4h. Could be worse.

**Comment by eparejatobes** [comment]
Should use data.uniprot 0.1.1

**Comment by eparejatobes** [comment]
I think I will finish this tomorrow. It needs more docs and less abstraction.

**Comment by laughedelic** [comment]
@eparejatobes can I help you anyhow here?

**Comment by eparejatobes** [comment]
@laughedelic and I already discussed this in person.

I'm merging this and finishing it in a separate PR, as I need to split out parsers from here etc.

**Pull request merged**
